version: "3.9"

networks:
  ms-network:
    driver: bridge

services:
  discovery-service:
    build:
      context: ./backend/discovery-service
      dockerfile: Dockerfile.prod
    ports:
      - "8761:8761"
    networks:
      - ms-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway-service:
    build:
      context: ./backend/gateway-service
      dockerfile: Dockerfile.prod
    ports:
      - "8760:8760"
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - ms-network
    environment:
      JWT_SECRET: ${JWT_SECRET}

  main-service:
    build:
      context: ./backend/main-service
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - ms-network
    environment:
      DEVLOG_GOOGLE_CLIENT_ID: ${DEVLOG_GOOGLE_CLIENT_ID}
      DEVLOG_GOOGLE_CLIENT_SECRET: ${DEVLOG_GOOGLE_CLIENT_SECRET}
      ORACLE_USERNAME: ${ORACLE_USERNAME}
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ${ORACLE_WALLET_PATH}:${ORACLE_WALLET_PATH}
      - /home/static/resource:/home/static/resource

  mail-service:
    build:
      context: ./backend/mail-service
      dockerfile: Dockerfile.prod
    ports:
      - "8001:8001"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - ms-network
    environment:
      DEVLOG_MAIL_USERNAME: ${DEVLOG_MAIL_USERNAME}
      DEVLOG_MAIL_PASSWORD: ${DEVLOG_MAIL_PASSWORD}

  llm-service:
    build:
      context: ./backend/llm-service
      dockerfile: Dockerfile.prod
    ports:
      - "8100:8100"
    networks:
      - ms-network
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ms-network

  dozzle:
    image: amir20/dozzle:latest
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ms-network
