version: "3.9"

networks:
  ms-network:
    driver: bridge

services:
  mainserver:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - ms-network
    environment:
      DEVLOG_GOOGLE_CLIENT_ID: ${DEVLOG_GOOGLE_CLIENT_ID}
      DEVLOG_GOOGLE_CLIENT_SECRET: ${DEVLOG_GOOGLE_CLIENT_SECRET}
      ORACLE_USERNAME: ${ORACLE_USERNAME}
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ${ORACLE_WALLET_PATH}:${ORACLE_WALLET_PATH}
      - /home/static/resource:/home/static/resource

  mailserver:
    build:
      context: ./mailserver
      dockerfile: Dockerfile.prod
    ports:
      - "8001:8001"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - ms-network
    environment:
      DEVLOG_MAIL_USERNAME: ${DEVLOG_MAIL_USERNAME}
      DEVLOG_MAIL_PASSWORD: ${DEVLOG_MAIL_PASSWORD}

  llmserver:
    build:
      context: ./llmserver
      dockerfile: Dockerfile.prod
    ports:
      - "8100:8100"
    networks:
      - ms-network
    environment:
      - OPENAI_API_KEY: ${OPENAI_API_KEY}

  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ms-network

  dozzle:
    image: amir20/dozzle:latest
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ms-network
