server:
  port: 8760

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/ # http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  config:
    import:
      - classpath:/yaml/application-local.yml
      - classpath:/yaml/application-prod.yml
  profiles:
    active: local
  cloud:
    config:
      enabled: false
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:3000,https://devlog.run"
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - content-type
              - credential
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
              - PATCH
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: main-service
          uri: lb://MAIN-SERVICE
          predicates:
            - Path=/main/**
          filters:
            - name: MainFilter
              args:
                baseMessage: Gateway MainFilter
                preLogger: true
                postLogger: true
            - RewritePath=/main/(?<segment>.*), /$\{segment}
        - id: llm-service
          uri: lb://LLM-SERVICE
          predicates:
            - Path=/llm/**
          filters:
            - RewritePath=/llm/(?<segment>.*), /$\{segment}

jwt:
  secret: ${JWT_SECRET}