spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-service:3306/devlog?serverTimezone=Asia/Seoul
    username: root
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create # DDL (create/update/create-drop/validate/none)
    properties:
      hibernate:
        show_sql: true
        format_sql: true
frontend:
  url: http://localhost:3000