spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@testdb_high?TNS_ADMIN=./src/main/resources/wallet
    username: ${ORACLE_USERNAME}
    password: ${ORACLE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create # DDL (create/update/create-drop/validate/none)
    properties:
      hibernate:
        show_sql: true
        format_sql: true
frontend:
  url: http://localhost:3000