server:
  shutdown: graceful

spring:
  lifecycle: timeout-per-shutdown-phase=30s
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@testdb_high?TNS_ADMIN=/home/app/backend/wallet
    username: ${ORACLE_USERNAME}
    password: ${ORACLE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # DDL (create/update/create-drop/validate/none)
    properties:
      hibernate:
        show_sql: true
        format_sql: true
frontend:
  url: https://devlog.run
  domain: devlog.run
file:
  upload:
    path: /home/resource
  request:
    path: res
# screen -S back java -jar devlog.jar --spring.profiles.active=prod
