spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@testdb_high?TNS_ADMIN=./src/main/resources/wallet
    username: ${ORACLE_USERNAME}
    password: ${ORACLE_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/devlog?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
#    username: root
#    password: ${MYSQL_PASSWORD}
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update # DDL (create/update/create-drop/validate/none)
    properties:
      hibernate:
        show_sql: true
        format_sql: true
frontend:
  url: http://localhost:3000