FROM gradle:jdk17

WORKDIR /app

RUN apt-get update && apt-get install -y tzdata

# 타임존 설정
ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY ./mail.jar .

ENTRYPOINT ["java", "-jar", "mail.jar", "--spring.profiles.active=prod"]