server:
  port: 8000

spring:
  config:
    import:
      - classpath:/yaml/application-local.yml
      - classpath:/yaml/application-dev.yml
      - classpath:/yaml/application-prod.yml
      - classpath:/yaml/application-docker.yml
  profiles:
    active: local
    include: oauth
  application:
    name: backend
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${DEVLOG_GOOGLE_CLIENT_ID}
            client-secret: ${DEVLOG_GOOGLE_CLIENT_SECRET}
            scope: profile, email
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

jwt:
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  secret: 1248678ec3a15d17b4b60cfa6e3cb3617f2de559ad9cb710bc693ab3d01f5a09955fefa111a924860978536dbd845519e2915356b3cd558d5ec8d2fa7584ab63
  access:
    header: Authorization
    expiration: 3600
  refresh:
    header: Authorization-Refresh
    expiration: 86400