server:
  port: 8000

spring:
  config:
    import:
      - classpath:/yaml/application-local-old.yml
      - classpath:/yaml/application-local.yml
      - classpath:/yaml/application-dev.yml
      - classpath:/yaml/application-prod.yml
  profiles:
    active: local
    include: oauth
  application:
    name: backend
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${DEVLOG_GOOGLE_CLIENT_ID}
            client-secret: ${DEVLOG_GOOGLE_CLIENT_SECRET}
            scope: profile, email
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

jwt:
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  secret: ${JWT_SECRET}
  access:
    header: Authorization # unused
    expiration: 3600
  refresh:
    header: Authorization-Refresh # unused
    expiration: 1209600