name: Frontend Continuous Delivery

on:
  push:
    paths:
      - "frontend/**"
    branches:
      - main
  workflow_dispatch:

permissions: write-all

env:
  ZIP_NAME: "frontend.tar"
  APP_TARGET_PATH: "frontend/"
  APP_FOLDER_PATH: "/home/app/frontend"

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Build Docker image
        run: docker build -f Dockerfile.prod -t devlog-frontend:latest .

      - name: Save Docker image as tar file
        run: docker save -o frontend.tar devlog-frontend:latest

      # (Actions에서 생성한 파일은 권한을 수정해야 scp로 보낼 때 오류가 안생김)
      - name: Modify permissions
        run: chmod o+rwx ${{ env.ZIP_NAME }}

      - name: Send build file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "${{ env.APP_TARGET_PATH }}${{ env.ZIP_NAME }}"
          target: ${{ env.APP_FOLDER_PATH }}
          strip_components: 1

      - name: Restart Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.APP_FOLDER_PATH }}
            docker load -i frontend.tar
            cd /home/app
            docker-compose -f docker-compose.prod.yml up -d frontend-service
