name: Backend Continuous Delivery

on:
  push:
    paths:
      - "backend/**"
      - "docker-compose.yml"
    branches:
      - main
  workflow_dispatch:

permissions: write-all

env:
  DEVLOG_GOOGLE_CLIENT_ID: ${{secrets.DEVLOG_GOOGLE_CLIENT_ID}}
  DEVLOG_GOOGLE_CLIENT_SECRET: ${{secrets.DEVLOG_GOOGLE_CLIENT_SECRET}}

  GATEWAY_JAR_TARGET_PATH: "backend/gateway-service/build/libs/gateway-service.jar"
  GATEWAY_DOCKER_TARGET_PATH: "backend/gateway-service/Dockerfile.prod"
  GATEWAY_FOLDER_PATH: "/home/app/backend/gateway-service"

  DISCOVERY_JAR_TARGET_PATH: "backend/discovery-service/build/libs/discovery-service.jar"
  DISCOVERY_DOCKER_TARGET_PATH: "backend/discovery-service/Dockerfile.prod"
  DISCOVERY_FOLDER_PATH: "/home/app/backend/discovery-service"

  MAIN_JAR_TARGET_PATH: "backend/main-service/build/libs/main-service.jar"
  MAIN_DOCKER_TARGET_PATH: "backend/main-service/Dockerfile.prod"
  MAIN_FOLDER_PATH: "/home/app/backend/main-service"

  MAIL_JAR_TARGET_PATH: "backend/mail-service/build/libs/mail-service.jar"
  MAIL_DOCKER_TARGET_PATH: "backend/mail-service/Dockerfile.prod"
  MAIL_FOLDER_PATH: "/home/app/backend/mail-service"

  LLM_ZIP_NAME: "llm-service.zip"
  LLM_ZIP_TARGET_PATH: "backend/llm-service/llm-service.zip"
  LLM_DOCKER_TARGET_PATH: "backend/llm-service/Dockerfile.prod"
  LLM_FOLDER_PATH: "/home/app/backend/llm-service"

jobs:
  # 사전 작업
  setup:
    runs-on: ubuntu-22.04
    # defaults:
    #   run:
    #     working-directory: backend
    outputs:
      discovery-build-cache-key: ${{ steps.discovery-build-cache.outputs.key }}
      gateway-build-cache-key: ${{ steps.gateway-build-cache.outputs.key }}
      main-build-cache-key: ${{ steps.main-build-cache.outputs.key }}
      mail-build-cache-key: ${{ steps.mail-build-cache.outputs.key }}
      current-datetime: ${{ steps.datetime.outputs.datetime }}
    steps:
      - uses: actions/checkout@v4

      - name: check
        run: ls -al

      - name: Get current date and time
        id: datetime
        run: echo "datetime=$(date '+%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Generate discovery-service build cache key
        id: discovery-build-cache
        run: echo "key=$(echo build-${{ runner.os }}-gradle-${{ hashFiles('backend/discovery-service/**/*.gradle*', 'backend/discovery-service/**/gradle-wrapper.properties') }})" >> $GITHUB_OUTPUT

      - name: Generate gateway-service build cache key
        id: gateway-build-cache
        run: echo "key=$(echo build-${{ runner.os }}-gradle-${{ hashFiles('backend/gateway-service/**/*.gradle*', 'backend/gateway-service/**/gradle-wrapper.properties') }})" >> $GITHUB_OUTPUT

      - name: Generate main-service build cache key
        id: main-build-cache
        run: echo "key=$(echo build-${{ runner.os }}-gradle-${{ hashFiles('backend/main-service/**/*.gradle*', 'backend/main-service/**/gradle-wrapper.properties') }})" >> $GITHUB_OUTPUT

      - name: Generate mail-service build cache key
        id: mail-build-cache
        run: echo "key=$(echo build-${{ runner.os }}-gradle-${{ hashFiles('backend/mail-service/**/*.gradle*', 'backend/mail-service/**/gradle-wrapper.properties') }})" >> $GITHUB_OUTPUT

      - name: Modify permissions
        run: chmod o+rwx docker-compose.prod.yml

      - name: Send docker-compose.prod.yml
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.prod.yml"
          target: "/home/app"

  build-discovery-service:
    needs: setup
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: backend/discovery-service
    steps:
      - uses: actions/checkout@v4

      - name: Gradle Caching
        id: cache-gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ needs.setup.outputs.discovery-build-cache-key }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Check
        if: steps.cache-gradle.outputs.cache-hit == 'true'
        run: echo 'Gradle cache hit!'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      # (Actions에서 생성한 파일은 권한을 수정해야 scp로 보낼 때 오류가 안생김)
      - name: Modify permissions
        run: chmod o+rwx build/libs/discovery-service.jar

      - name: Send jar
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ${{ env.DISCOVERY_JAR_TARGET_PATH }}
          target: ${{ env.DISCOVERY_FOLDER_PATH }}
          strip_components: 4 # 파일을 복사할 때 source 경로에서 몇 개의 컴포넌트(디렉토리)를 제거할 것인지를 지정합니다. 4이므로, backend/main-service/build/libs/devlog.jar 에서 backend, main-service, build, libs가 사라짐.

      - name: Modify permissions Dockerfile.prod
        run: chmod o+rwx Dockerfile.prod

      - name: Send Dockerfile.prod
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ${{ env.DISCOVERY_DOCKER_TARGET_PATH }}
          target: ${{ env.DISCOVERY_FOLDER_PATH }}
          strip_components: 2

  build-gateway-service:
    needs: setup
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: backend/gateway-service
    steps:
      - uses: actions/checkout@v4

      - name: Gradle Caching
        id: cache-gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ needs.setup.outputs.gateway-build-cache-key }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Check
        if: steps.cache-gradle.outputs.cache-hit == 'true'
        run: echo 'Gradle cache hit!'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      # (Actions에서 생성한 파일은 권한을 수정해야 scp로 보낼 때 오류가 안생김)
      - name: Modify permissions
        run: chmod o+rwx build/libs/gateway-service.jar

      - name: Send jar
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ${{ env.GATEWAY_JAR_TARGET_PATH }}
          target: ${{ env.GATEWAY_FOLDER_PATH }}
          strip_components: 4 # 파일을 복사할 때 source 경로에서 몇 개의 컴포넌트(디렉토리)를 제거할 것인지를 지정합니다. 4이므로, backend/main-service/build/libs/devlog.jar 에서 backend, main-service, build, libs가 사라짐.

      - name: Modify permissions Dockerfile.prod
        run: chmod o+rwx Dockerfile.prod

      - name: Send Dockerfile.prod
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ${{ env.GATEWAY_DOCKER_TARGET_PATH }}
          target: ${{ env.GATEWAY_FOLDER_PATH }}
          strip_components: 2

  build-main-service:
    needs: setup
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: backend/main-service
    steps:
      - uses: actions/checkout@v4

      - name: Gradle Caching
        id: cache-gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ needs.setup.outputs.main-build-cache-key }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Check
        if: steps.cache-gradle.outputs.cache-hit == 'true'
        run: echo 'Gradle cache hit!'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      # (Actions에서 생성한 파일은 권한을 수정해야 scp로 보낼 때 오류가 안생김)
      - name: Modify permissions
        run: chmod o+rwx build/libs/main-service.jar

      - name: Send jar
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ${{ env.MAIN_JAR_TARGET_PATH }}
          target: ${{ env.MAIN_FOLDER_PATH }}
          strip_components: 4 # 파일을 복사할 때 source 경로에서 몇 개의 컴포넌트(디렉토리)를 제거할 것인지를 지정합니다. 4이므로, backend/main-service/build/libs/devlog.jar 에서 backend, main-service, build, libs가 사라짐.

      - name: Modify permissions Dockerfile.prod
        run: chmod o+rwx Dockerfile.prod

      - name: Send Dockerfile.prod
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ${{ env.MAIN_DOCKER_TARGET_PATH }}
          target: ${{ env.MAIN_FOLDER_PATH }}
          strip_components: 2

  build-mail-service:
    needs: setup
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: backend/mail-service
    steps:
      - uses: actions/checkout@v4

      - name: Gradle Caching
        id: cache-gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ needs.setup.outputs.mail-build-cache-key }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Check
        if: steps.cache-gradle.outputs.cache-hit == 'true'
        run: echo 'Gradle cache hit!'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      # (Actions에서 생성한 파일은 권한을 수정해야 scp로 보낼 때 오류가 안생김)
      - name: Modify permissions
        run: chmod o+rwx build/libs/mail-service.jar

      - name: Send jar
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ${{ env.MAIL_JAR_TARGET_PATH }}
          target: ${{ env.MAIL_FOLDER_PATH }}
          strip_components: 4

      - name: Modify permissions Dockerfile.prod
        run: chmod o+rwx Dockerfile.prod

      - name: Send Dockerfile.prod
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ${{ env.MAIL_DOCKER_TARGET_PATH }}
          target: ${{ env.MAIL_FOLDER_PATH }}
          strip_components: 2

  build-llm-service:
    needs: setup
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: backend/llm-service
    steps:
      - uses: actions/checkout@v4

      - name: Make zip file
        run: zip -qq -r ./${{ env.LLM_ZIP_NAME }} . -x ".git/*" ".github/*"

      # (Actions에서 생성한 파일은 권한을 수정해야 scp로 보낼 때 오류가 안생김)
      - name: Modify permissions of Zip file
        run: chmod o+rwx ${{ env.LLM_ZIP_NAME }}

      - name: Send Zip file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ${{ env.LLM_ZIP_TARGET_PATH }}
          target: ${{ env.LLM_FOLDER_PATH }}
          strip_components: 2

      - name: Modify permissions Dockerfile.prod
        run: chmod o+rwx Dockerfile.prod

      - name: Send Dockerfile.prod
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ${{ env.LLM_DOCKER_TARGET_PATH }}
          target: ${{ env.LLM_FOLDER_PATH }}
          strip_components: 2

      - name: Unzip
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/app/backend/llm-service
            unzip -o ${{ env.LLM_ZIP_NAME }}

  startup:
    needs:
      - build-discovery-service
      - build-gateway-service
      - build-main-service
      - build-mail-service
      - build-llm-service
    runs-on: ubuntu-22.04
    steps:
      - name: Restart Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/app
            docker-compose -f docker-compose.prod.yml down --rmi all --remove-orphans
            docker-compose -f docker-compose.prod.yml up -d --build
